// Code generated from @tensorflow-models/mobilenet's dist/imagenet_classes.js
// (the exact data the frontend's MobileNet model returns at runtime), by
// splitting each of its 1000 class entries on commas — some entries list
// several synonyms as one string (e.g. "tabby, tabby cat"), and the frontend's
// matching logic (see frontend/src/lib/detector.ts) treats a match against any
// one synonym as valid, so this set does too. Regenerate by re-running the
// extraction script recorded in the PR that introduced this file if the
// mobilenet package version changes.
package db

var imagenetTokens = map[string]bool{
	"abacus": true,
	"abaya": true,
	"academic gown": true,
	"academic robe": true,
	"accordion": true,
	"acinonyx jubatus": true,
	"acorn": true,
	"acorn squash": true,
	"acoustic guitar": true,
	"admiral": true,
	"aegis": true,
	"aepyceros melampus": true,
	"affenpinscher": true,
	"afghan": true,
	"afghan hound": true,
	"african chameleon": true,
	"african crocodile": true,
	"african elephant": true,
	"african gray": true,
	"african grey": true,
	"african hunting dog": true,
	"agama": true,
	"agaric": true,
	"ai": true,
	"ailuropoda melanoleuca": true,
	"ailurus fulgens": true,
	"aircraft carrier": true,
	"airedale": true,
	"airedale terrier": true,
	"airliner": true,
	"airship": true,
	"alaska crab": true,
	"alaska king crab": true,
	"alaskan king crab": true,
	"alaskan malamute": true,
	"albatross": true,
	"all-terrain bike": true,
	"alligator lizard": true,
	"alligator mississipiensis": true,
	"alopex lagopus": true,
	"alp": true,
	"alsatian": true,
	"altar": true,
	"ambulance": true,
	"ambystoma maculatum": true,
	"ambystoma mexicanum": true,
	"american alligator": true,
	"american black bear": true,
	"american chameleon": true,
	"american coot": true,
	"american eagle": true,
	"american egret": true,
	"american lobster": true,
	"american pit": true,
	"american robin": true,
	"american staffordshire terrier": true,
	"amphibian": true,
	"amphibious vehicle": true,
	"analog clock": true,
	"ananas": true,
	"anemone": true,
	"anemone fish": true,
	"angora": true,
	"angora rabbit": true,
	"anole": true,
	"anolis carolinensis": true,
	"ant": true,
	"anteater": true,
	"apiary": true,
	"appenzeller": true,
	"apron": true,
	"aptenodytes patagonica": true,
	"arabian camel": true,
	"aramus pictus": true,
	"aranea diademata": true,
	"araneus cavaticus": true,
	"arctic fox": true,
	"arctic wolf": true,
	"arenaria interpres": true,
	"argiope aurantia": true,
	"armadillo": true,
	"armored combat vehicle": true,
	"armoured combat vehicle": true,
	"army tank": true,
	"artichoke": true,
	"articulated": true,
	"ascaphus trui": true,
	"ash bin": true,
	"ash-bin": true,
	"ashbin": true,
	"ashcan": true,
	"asiatic buffalo": true,
	"assault gun": true,
	"assault rifle": true,
	"ateles geoffroyi": true,
	"attack aircraft carrier": true,
	"australian terrier": true,
	"automated teller machine": true,
	"automatic": true,
	"automatic washer": true,
	"axolotl": true,
	"baboon": true,
	"back pack": true,
	"backpack": true,
	"badger": true,
	"bagel": true,
	"bakehouse": true,
	"bakery": true,
	"bakeshop": true,
	"balance beam": true,
	"bald eagle": true,
	"balloon": true,
	"ballpen": true,
	"ballplayer": true,
	"ballpoint": true,
	"ballpoint pen": true,
	"balusters": true,
	"balustrade": true,
	"banana": true,
	"band aid": true,
	"bandeau": true,
	"banded gecko": true,
	"banister": true,
	"banjo": true,
	"bannister": true,
	"barbell": true,
	"barber chair": true,
	"barbershop": true,
	"barn": true,
	"barn spider": true,
	"barometer": true,
	"barracouta": true,
	"barrel": true,
	"barrow": true,
	"bars": true,
	"baseball": true,
	"baseball player": true,
	"basenji": true,
	"basketball": true,
	"basset": true,
	"basset hound": true,
	"bassinet": true,
	"bassoon": true,
	"bath": true,
	"bath towel": true,
	"bathing cap": true,
	"bathing trunks": true,
	"bathing tub": true,
	"bathroom tissue": true,
	"bathtub": true,
	"beach waggon": true,
	"beach wagon": true,
	"beacon": true,
	"beacon light": true,
	"beagle": true,
	"beaker": true,
	"beam": true,
	"bear cat": true,
	"bearskin": true,
	"beaver": true,
	"bedlington terrier": true,
	"bee": true,
	"bee eater": true,
	"bee house": true,
	"beer bottle": true,
	"beer glass": true,
	"beigel": true,
	"bell": true,
	"bell cot": true,
	"bell cote": true,
	"bell pepper": true,
	"bell toad": true,
	"bernese mountain dog": true,
	"bib": true,
	"bicycle-built-for-two": true,
	"bighorn": true,
	"bighorn sheep": true,
	"bikini": true,
	"billfish": true,
	"billfold": true,
	"billiard table": true,
	"binder": true,
	"binoculars": true,
	"birdhouse": true,
	"biro": true,
	"bison": true,
	"bittern": true,
	"black": true,
	"black and gold garden spider": true,
	"black bear": true,
	"black grouse": true,
	"black stork": true,
	"black swan": true,
	"black widow": true,
	"black-and-tan coonhound": true,
	"black-footed ferret": true,
	"blenheim spaniel": true,
	"bloodhound": true,
	"blow drier": true,
	"blow dryer": true,
	"blower": true,
	"blowfish": true,
	"blue jack": true,
	"blue jean": true,
	"bluetick": true,
	"boa": true,
	"boa constrictor": true,
	"boar": true,
	"board": true,
	"boat paddle": true,
	"boathouse": true,
	"bob": true,
	"bobsled": true,
	"bobsleigh": true,
	"bobtail": true,
	"bola": true,
	"bola tie": true,
	"bolete": true,
	"bolo": true,
	"bolo tie": true,
	"bonasa umbellus": true,
	"bonnet": true,
	"book jacket": true,
	"bookcase": true,
	"bookshop": true,
	"bookstall": true,
	"bookstore": true,
	"border collie": true,
	"border terrier": true,
	"borzoi": true,
	"boston bull": true,
	"boston terrier": true,
	"bottle screw": true,
	"bottlecap": true,
	"bouvier des flandres": true,
	"bouviers des flandres": true,
	"bow": true,
	"bow tie": true,
	"bow-tie": true,
	"bowtie": true,
	"box tortoise": true,
	"box turtle": true,
	"boxer": true,
	"bra": true,
	"brabancon griffon": true,
	"bradypus tridactylus": true,
	"brain coral": true,
	"brambling": true,
	"brass": true,
	"brassiere": true,
	"breakwater": true,
	"breastplate": true,
	"briard": true,
	"bridegroom": true,
	"brittany spaniel": true,
	"broccoli": true,
	"broom": true,
	"brown bear": true,
	"bruin": true,
	"brush kangaroo": true,
	"brush wolf": true,
	"bubalus bubalis": true,
	"bubble": true,
	"bucket": true,
	"buckeye": true,
	"buckle": true,
	"buckler": true,
	"bulbul": true,
	"bull mastiff": true,
	"bullet": true,
	"bullet train": true,
	"bulletproof vest": true,
	"bullfrog": true,
	"bulwark": true,
	"burrito": true,
	"busby": true,
	"bustard": true,
	"butcher shop": true,
	"butternut squash": true,
	"cab": true,
	"cabbage butterfly": true,
	"cacatua galerita": true,
	"cairn": true,
	"cairn terrier": true,
	"caldron": true,
	"camelus dromedarius": true,
	"can opener": true,
	"cancer irroratus": true,
	"cancer magister": true,
	"candle": true,
	"candy store": true,
	"canis dingo": true,
	"canis latrans": true,
	"canis lupus": true,
	"canis lupus tundrarum": true,
	"canis niger": true,
	"canis rufus": true,
	"cannon": true,
	"canoe": true,
	"cape hunting dog": true,
	"capitulum": true,
	"capra ibex": true,
	"capuchin": true,
	"car mirror": true,
	"car wheel": true,
	"carabid beetle": true,
	"carassius auratus": true,
	"carbonara": true,
	"cardigan": true,
	"cardigan welsh corgi": true,
	"cardoon": true,
	"carduelis carduelis": true,
	"caretta caretta": true,
	"carousel": true,
	"carpenter\\": true,
	"carphophis amoenus": true,
	"carpodacus mexicanus": true,
	"carriage": true,
	"carriage dog": true,
	"carrier": true,
	"carrion fungus": true,
	"carrousel": true,
	"carton": true,
	"cash dispenser": true,
	"cash machine": true,
	"cask": true,
	"cassette": true,
	"cassette player": true,
	"castle": true,
	"cat bear": true,
	"catamaran": true,
	"catamount": true,
	"cathode-ray oscilloscope": true,
	"cauldron": true,
	"cauliflower": true,
	"cavia cobaya": true,
	"cd player": true,
	"cebus capucinus": true,
	"cell": true,
	"cello": true,
	"cellphone": true,
	"cellular phone": true,
	"cellular telephone": true,
	"centipede": true,
	"cerastes": true,
	"cerastes cornutus": true,
	"chain": true,
	"chain armor": true,
	"chain armour": true,
	"chain mail": true,
	"chain saw": true,
	"chainlink fence": true,
	"chainsaw": true,
	"chamaeleo chamaeleon": true,
	"chambered nautilus": true,
	"cheeseburger": true,
	"cheetah": true,
	"chesapeake bay retriever": true,
	"chest": true,
	"chetah": true,
	"chickadee": true,
	"chiffonier": true,
	"chihuahua": true,
	"chime": true,
	"chimp": true,
	"chimpanzee": true,
	"china cabinet": true,
	"china closet": true,
	"chiton": true,
	"chlamydosaurus kingi": true,
	"chocolate sauce": true,
	"chocolate syrup": true,
	"chopper": true,
	"chow": true,
	"chow chow": true,
	"christmas stocking": true,
	"chrysanthemum dog": true,
	"chrysomelid": true,
	"church": true,
	"church building": true,
	"chute": true,
	"cicada": true,
	"cicala": true,
	"ciconia ciconia": true,
	"ciconia nigra": true,
	"cimarron": true,
	"cinema": true,
	"claw": true,
	"cleaver": true,
	"cliff": true,
	"cliff dwelling": true,
	"cloak": true,
	"clog": true,
	"closet": true,
	"clumber": true,
	"clumber spaniel": true,
	"coach": true,
	"coach dog": true,
	"coast": true,
	"coat-of-mail shell": true,
	"cock": true,
	"cocker": true,
	"cocker spaniel": true,
	"cockroach": true,
	"cocktail shaker": true,
	"coffee mug": true,
	"coffeepot": true,
	"coho": true,
	"coho salmon": true,
	"cohoe": true,
	"coil": true,
	"collie": true,
	"colobus": true,
	"colobus monkey": true,
	"combination lock": true,
	"comfort": true,
	"comforter": true,
	"comic book": true,
	"commode": true,
	"common iguana": true,
	"common newt": true,
	"computer keyboard": true,
	"computer mouse": true,
	"conch": true,
	"confectionary": true,
	"confectionery": true,
	"conker": true,
	"consomme": true,
	"constrictor constrictor": true,
	"container ship": true,
	"container vessel": true,
	"containership": true,
	"convertible": true,
	"coon bear": true,
	"coral fungus": true,
	"coral reef": true,
	"corkscrew": true,
	"corn": true,
	"cornet": true,
	"cot": true,
	"cottontail": true,
	"cottontail rabbit": true,
	"coucal": true,
	"cougar": true,
	"courgette": true,
	"cowboy boot": true,
	"cowboy hat": true,
	"coyote": true,
	"cradle": true,
	"crampfish": true,
	"crane": true,
	"crash helmet": true,
	"crate": true,
	"crawdad": true,
	"crawdaddy": true,
	"crawfish": true,
	"crayfish": true,
	"crib": true,
	"cricket": true,
	"crinoline": true,
	"cro": true,
	"crock pot": true,
	"crocodylus niloticus": true,
	"croquet ball": true,
	"crossword": true,
	"crossword puzzle": true,
	"crotalus adamanteus": true,
	"crotalus cerastes": true,
	"crt screen": true,
	"crutch": true,
	"cucumber": true,
	"cuirass": true,
	"cuke": true,
	"cuon alpinus": true,
	"cup": true,
	"curly-coated retriever": true,
	"custard apple": true,
	"cygnus atratus": true,
	"daddy longlegs": true,
	"daisy": true,
	"dalmatian": true,
	"dam": true,
	"damselfly": true,
	"danaus plexippus": true,
	"dandie dinmont": true,
	"dandie dinmont terrier": true,
	"dark glasses": true,
	"darning needle": true,
	"day bed": true,
	"deerhound": true,
	"denim": true,
	"dermochelys coriacea": true,
	"desk": true,
	"desktop computer": true,
	"devil\\": true,
	"devilfish": true,
	"dhole": true,
	"dial phone": true,
	"dial telephone": true,
	"diamondback": true,
	"diamondback rattlesnake": true,
	"diaper": true,
	"digital clock": true,
	"digital watch": true,
	"dike": true,
	"dingo": true,
	"dining table": true,
	"dipper": true,
	"dirigible": true,
	"disc brake": true,
	"dish washer": true,
	"dishcloth": true,
	"dishrag": true,
	"dishwasher": true,
	"dishwashing machine": true,
	"disk brake": true,
	"doberman": true,
	"doberman pinscher": true,
	"dock": true,
	"dockage": true,
	"docking facility": true,
	"dog sled": true,
	"dog sleigh": true,
	"dogsled": true,
	"dome": true,
	"doormat": true,
	"dough": true,
	"dowitcher": true,
	"dragon lizard": true,
	"dragonfly": true,
	"drake": true,
	"drilling platform": true,
	"dromedary": true,
	"drop": true,
	"drop-off": true,
	"drum": true,
	"drumstick": true,
	"duck-billed platypus": true,
	"duckbill": true,
	"duckbilled platypus": true,
	"dugong": true,
	"dugong dugon": true,
	"dumbbell": true,
	"dung beetle": true,
	"dungeness crab": true,
	"dunlin": true,
	"dust cover": true,
	"dust jacket": true,
	"dust wrapper": true,
	"dustcart": true,
	"dutch oven": true,
	"dyke": true,
	"ear": true,
	"earthstar": true,
	"eastern fox squirrel": true,
	"eatery": true,
	"eating house": true,
	"eating place": true,
	"echidna": true,
	"eel": true,
	"eft": true,
	"eggnog": true,
	"egis": true,
	"egretta albus": true,
	"egretta caerulea": true,
	"egyptian cat": true,
	"electric fan": true,
	"electric guitar": true,
	"electric locomotive": true,
	"electric ray": true,
	"electric switch": true,
	"electrical switch": true,
	"elephas maximus": true,
	"elkhound": true,
	"emmet": true,
	"english cocker spaniel": true,
	"english foxhound": true,
	"english setter": true,
	"english springer": true,
	"english springer spaniel": true,
	"entertainment center": true,
	"entlebucher": true,
	"envelope": true,
	"erolia alpina": true,
	"erythrocebus patas": true,
	"eschrichtius gibbosus": true,
	"eskimo dog": true,
	"espresso": true,
	"espresso maker": true,
	"essence": true,
	"estate car": true,
	"euarctos": true,
	"european fire salamander": true,
	"european gallinule": true,
	"ewer": true,
	"face powder": true,
	"feather boa": true,
	"felis onca": true,
	"ferret": true,
	"fiddle": true,
	"fiddler crab": true,
	"field glasses": true,
	"fig": true,
	"file": true,
	"file cabinet": true,
	"filing cabinet": true,
	"fire engine": true,
	"fire screen": true,
	"fire truck": true,
	"fireboat": true,
	"fireguard": true,
	"fitch": true,
	"fixed disk": true,
	"flagpole": true,
	"flagstaff": true,
	"flamingo": true,
	"flat-coated retriever": true,
	"flattop": true,
	"flatworm": true,
	"flowerpot": true,
	"flute": true,
	"fly": true,
	"folding chair": true,
	"food market": true,
	"football helmet": true,
	"footstall": true,
	"foreland": true,
	"forklift": true,
	"foulmart": true,
	"foumart": true,
	"fountain": true,
	"fountain pen": true,
	"four-poster": true,
	"fox squirrel": true,
	"freight car": true,
	"french bulldog": true,
	"french horn": true,
	"french loaf": true,
	"frilled lizard": true,
	"fringilla montifringilla": true,
	"frying pan": true,
	"frypan": true,
	"fulica americana": true,
	"fur coat": true,
	"galeocerdo cuvieri": true,
	"gar": true,
	"garbage can": true,
	"garbage truck": true,
	"garden cart": true,
	"garden spider": true,
	"garfish": true,
	"garpike": true,
	"garter snake": true,
	"gas helmet": true,
	"gas pump": true,
	"gasmask": true,
	"gasoline pump": true,
	"gazelle": true,
	"gazelle hound": true,
	"german police dog": true,
	"german shepherd": true,
	"german shepherd dog": true,
	"german short-haired pointer": true,
	"geta": true,
	"geyser": true,
	"giant lizard": true,
	"giant panda": true,
	"giant schnauzer": true,
	"gibbon": true,
	"gila monster": true,
	"glasshouse": true,
	"globe artichoke": true,
	"globefish": true,
	"go-kart": true,
	"goblet": true,
	"golden retriever": true,
	"goldfinch": true,
	"goldfish": true,
	"golf ball": true,
	"golf cart": true,
	"golfcart": true,
	"gondola": true,
	"gong": true,
	"goose": true,
	"gordon setter": true,
	"gorilla": true,
	"gorilla gorilla": true,
	"gown": true,
	"grampus": true,
	"grand": true,
	"grand piano": true,
	"granny smith": true,
	"grass snake": true,
	"grasshopper": true,
	"gray fox": true,
	"gray whale": true,
	"gray wolf": true,
	"great dane": true,
	"great gray owl": true,
	"great grey owl": true,
	"great pyrenees": true,
	"great white heron": true,
	"great white shark": true,
	"greater swiss mountain dog": true,
	"green lizard": true,
	"green mamba": true,
	"green snake": true,
	"greenhouse": true,
	"grey fox": true,
	"grey whale": true,
	"grey wolf": true,
	"grifola": true,
	"grille": true,
	"grocery": true,
	"grocery store": true,
	"groenendael": true,
	"groin": true,
	"groom": true,
	"ground beetle": true,
	"groyne": true,
	"grunter": true,
	"guacamole": true,
	"guenon": true,
	"guenon monkey": true,
	"guillotine": true,
	"guinea pig": true,
	"gyromitra": true,
	"hack": true,
	"hair drier": true,
	"hair dryer": true,
	"hair slide": true,
	"hair spray": true,
	"half track": true,
	"haliaeetus leucocephalus": true,
	"hammer": true,
	"hammerhead": true,
	"hammerhead shark": true,
	"hamper": true,
	"hamster": true,
	"hand blower": true,
	"hand-held computer": true,
	"hand-held microcomputer": true,
	"handbasin": true,
	"handkerchief": true,
	"handrail": true,
	"hankey": true,
	"hankie": true,
	"hanky": true,
	"hard disc": true,
	"hard disk": true,
	"hare": true,
	"harmonica": true,
	"harp": true,
	"hartebeest": true,
	"harvester": true,
	"harvestman": true,
	"hatchet": true,
	"hautbois": true,
	"hautboy": true,
	"haversack": true,
	"hay": true,
	"head": true,
	"head cabbage": true,
	"headland": true,
	"hedgehog": true,
	"helix": true,
	"heloderma suspectum": true,
	"hen": true,
	"hen of the woods": true,
	"hen-of-the-woods": true,
	"hermit crab": true,
	"high bar": true,
	"hip": true,
	"hippo": true,
	"hippopotamus": true,
	"hippopotamus amphibius": true,
	"hockey puck": true,
	"hodometer": true,
	"hog": true,
	"hognose snake": true,
	"holocanthus tricolor": true,
	"holothurian": true,
	"holster": true,
	"homarus americanus": true,
	"home theater": true,
	"home theatre": true,
	"honeycomb": true,
	"hook": true,
	"hoopskirt": true,
	"hopper": true,
	"horizontal bar": true,
	"horn": true,
	"hornbill": true,
	"horned asp": true,
	"horned rattlesnake": true,
	"horned viper": true,
	"horse cart": true,
	"horse chestnut": true,
	"horse-cart": true,
	"hot dog": true,
	"hot pot": true,
	"hotdog": true,
	"hotpot": true,
	"hourglass": true,
	"house finch": true,
	"howler": true,
	"howler monkey": true,
	"hummingbird": true,
	"hungarian pointer": true,
	"hunting spider": true,
	"husky": true,
	"hussar monkey": true,
	"hyaena": true,
	"hyena": true,
	"hyena dog": true,
	"hylobates lar": true,
	"hylobates syndactylus": true,
	"hypsiglena torquata": true,
	"ibex": true,
	"ibizan hound": true,
	"ibizan podenco": true,
	"ice bear": true,
	"ice cream": true,
	"ice lolly": true,
	"icebox": true,
	"icecream": true,
	"igniter": true,
	"ignitor": true,
	"iguana": true,
	"iguana iguana": true,
	"impala": true,
	"indian cobra": true,
	"indian elephant": true,
	"indigo bird": true,
	"indigo bunting": true,
	"indigo finch": true,
	"indri": true,
	"indri brevicaudatus": true,
	"indri indri": true,
	"indris": true,
	"internet site": true,
	"ipod": true,
	"irish setter": true,
	"irish terrier": true,
	"irish water spaniel": true,
	"irish wolfhound": true,
	"iron": true,
	"island dispenser": true,
	"isopod": true,
	"italian greyhound": true,
	"jacamar": true,
	"jack": true,
	"jack-o\\": true,
	"jackfruit": true,
	"jaguar": true,
	"jak": true,
	"japanese spaniel": true,
	"jay": true,
	"jean": true,
	"jeep": true,
	"jelly fish": true,
	"jersey": true,
	"jetty": true,
	"jeweler\\": true,
	"jigsaw puzzle": true,
	"jinrikisha": true,
	"joystick": true,
	"judge\\": true,
	"junco": true,
	"kakatoe galerita": true,
	"kangaroo bear": true,
	"keeshond": true,
	"kelpie": true,
	"kerry blue terrier": true,
	"keypad": true,
	"killer": true,
	"killer whale": true,
	"kimono": true,
	"king crab": true,
	"king of beasts": true,
	"king penguin": true,
	"king snake": true,
	"kingsnake": true,
	"kit fox": true,
	"kite": true,
	"knapsack": true,
	"knee pad": true,
	"knot": true,
	"koala": true,
	"koala bear": true,
	"komodo dragon": true,
	"komodo lizard": true,
	"komondor": true,
	"kuvasz": true,
	"lab coat": true,
	"laboratory coat": true,
	"labrador retriever": true,
	"labyrinth": true,
	"lacerta viridis": true,
	"lacewing": true,
	"lacewing fly": true,
	"ladle": true,
	"lady beetle": true,
	"ladybeetle": true,
	"ladybird": true,
	"ladybird beetle": true,
	"ladybug": true,
	"lakeland terrier": true,
	"lakeshore": true,
	"lakeside": true,
	"lamp shade": true,
	"lampshade": true,
	"landrover": true,
	"langouste": true,
	"langur": true,
	"laptop": true,
	"laptop computer": true,
	"latrodectus mactans": true,
	"lavabo": true,
	"lawn cart": true,
	"lawn mower": true,
	"leaf beetle": true,
	"leafhopper": true,
	"leatherback": true,
	"leatherback turtle": true,
	"leathery turtle": true,
	"lemon": true,
	"lemur catta": true,
	"lens cap": true,
	"lens cover": true,
	"leonberg": true,
	"leopard": true,
	"lepisosteus osseus": true,
	"lesser panda": true,
	"letter box": true,
	"letter opener": true,
	"lhasa": true,
	"lhasa apso": true,
	"library": true,
	"lifeboat": true,
	"light": true,
	"lighter": true,
	"lighthouse": true,
	"limo": true,
	"limousine": true,
	"limpkin": true,
	"liner": true,
	"linnet": true,
	"lion": true,
	"lionfish": true,
	"lip rouge": true,
	"lipstick": true,
	"little blue heron": true,
	"llama": true,
	"loafer": true,
	"loggerhead": true,
	"loggerhead turtle": true,
	"lollipop": true,
	"lolly": true,
	"long-horned beetle": true,
	"longicorn": true,
	"longicorn beetle": true,
	"lorikeet": true,
	"lotion": true,
	"loudspeaker": true,
	"loudspeaker system": true,
	"loupe": true,
	"loxodonta africana": true,
	"lumbermill": true,
	"lycaenid": true,
	"lycaenid butterfly": true,
	"lycaon pictus": true,
	"lynx": true,
	"macaque": true,
	"macaw": true,
	"madagascar cat": true,
	"magnetic compass": true,
	"magpie": true,
	"mail": true,
	"mailbag": true,
	"mailbox": true,
	"maillot": true,
	"maine lobster": true,
	"malamute": true,
	"malemute": true,
	"malinois": true,
	"maltese": true,
	"maltese dog": true,
	"maltese terrier": true,
	"man-eater": true,
	"man-eating shark": true,
	"maned wolf": true,
	"manhole cover": true,
	"mantid": true,
	"mantis": true,
	"manufactured home": true,
	"maraca": true,
	"marimba": true,
	"market": true,
	"marmoset": true,
	"marmot": true,
	"marsh hen": true,
	"mashed potato": true,
	"mask": true,
	"matchstick": true,
	"maypole": true,
	"maze": true,
	"measuring cup": true,
	"meat cleaver": true,
	"meat loaf": true,
	"meat market": true,
	"meatloaf": true,
	"medicine cabinet": true,
	"medicine chest": true,
	"meerkat": true,
	"megalith": true,
	"megalithic structure": true,
	"melursus ursinus": true,
	"membranophone": true,
	"memorial tablet": true,
	"menu": true,
	"mergus serrator": true,
	"merry-go-round": true,
	"mexican hairless": true,
	"microphone": true,
	"microwave": true,
	"microwave oven": true,
	"mierkat": true,
	"mike": true,
	"mileometer": true,
	"military plane": true,
	"military uniform": true,
	"milk can": true,
	"milkweed butterfly": true,
	"milometer": true,
	"mini": true,
	"miniature pinscher": true,
	"miniature poodle": true,
	"miniature schnauzer": true,
	"minibus": true,
	"miniskirt": true,
	"minivan": true,
	"mink": true,
	"missile": true,
	"mitten": true,
	"mixing bowl": true,
	"mobile home": true,
	"mobile phone": true,
	"model t": true,
	"modem": true,
	"mole": true,
	"mollymawk": true,
	"monarch": true,
	"monarch butterfly": true,
	"monastery": true,
	"mongoose": true,
	"monitor": true,
	"monkey dog": true,
	"monkey pinscher": true,
	"monocycle": true,
	"mop": true,
	"moped": true,
	"mortar": true,
	"mortarboard": true,
	"mosque": true,
	"mosquito net": true,
	"motor scooter": true,
	"mountain bike": true,
	"mountain lion": true,
	"mountain tent": true,
	"mouse": true,
	"mousetrap": true,
	"mouth harp": true,
	"mouth organ": true,
	"movie house": true,
	"movie theater": true,
	"movie theatre": true,
	"moving van": true,
	"mower": true,
	"mud hen": true,
	"mud puppy": true,
	"mud turtle": true,
	"mushroom": true,
	"mustela nigripes": true,
	"mustela putorius": true,
	"muzzle": true,
	"nail": true,
	"naja naja": true,
	"napkin": true,
	"nappy": true,
	"nasalis larvatus": true,
	"native bear": true,
	"nautilus": true,
	"neck brace": true,
	"necklace": true,
	"nematode": true,
	"nematode worm": true,
	"newfoundland": true,
	"newfoundland dog": true,
	"night snake": true,
	"nile crocodile": true,
	"nipple": true,
	"norfolk terrier": true,
	"northern lobster": true,
	"norwegian elkhound": true,
	"norwich terrier": true,
	"notebook": true,
	"notebook computer": true,
	"notecase": true,
	"nudibranch": true,
	"numbfish": true,
	"nursery": true,
	"obelisk": true,
	"oboe": true,
	"ocarina": true,
	"ocean liner": true,
	"odometer": true,
	"off-roader": true,
	"offshore rig": true,
	"oil filter": true,
	"old english sheepdog": true,
	"oncorhynchus": true,
	"one-armed bandit": true,
	"opera glasses": true,
	"orang": true,
	"orange": true,
	"orangutan": true,
	"orangutang": true,
	"orca": true,
	"orcinus orca": true,
	"organ": true,
	"oscilloscope": true,
	"ostrich": true,
	"otter": true,
	"otter hound": true,
	"otterhound": true,
	"ounce": true,
	"overskirt": true,
	"ox": true,
	"oxcart": true,
	"oxygen mask": true,
	"oyster catcher": true,
	"oystercatcher": true,
	"packet": true,
	"packsack": true,
	"paddle": true,
	"paddle wheel": true,
	"paddlewheel": true,
	"paddy wagon": true,
	"padlock": true,
	"pail": true,
	"paintbrush": true,
	"painter": true,
	"pajama": true,
	"palace": true,
	"paling": true,
	"pan troglodytes": true,
	"panda": true,
	"panda bear": true,
	"pandean pipe": true,
	"panpipe": true,
	"panther": true,
	"panthera leo": true,
	"panthera onca": true,
	"panthera pardus": true,
	"panthera tigris": true,
	"panthera uncia": true,
	"paper knife": true,
	"paper towel": true,
	"paperknife": true,
	"papillon": true,
	"parachute": true,
	"parallel bars": true,
	"park bench": true,
	"parking meter": true,
	"partridge": true,
	"passenger car": true,
	"passerina cyanea": true,
	"patas": true,
	"patio": true,
	"patrol wagon": true,
	"patten": true,
	"pay-phone": true,
	"pay-station": true,
	"peacock": true,
	"pearly nautilus": true,
	"pedestal": true,
	"peke": true,
	"pekinese": true,
	"pekingese": true,
	"pelican": true,
	"pembroke": true,
	"pembroke welsh corgi": true,
	"pencil box": true,
	"pencil case": true,
	"pencil eraser": true,
	"pencil sharpener": true,
	"penny bank": true,
	"perfume": true,
	"persian cat": true,
	"petri dish": true,
	"petrol pump": true,
	"phalangium opilio": true,
	"pharos": true,
	"phascolarctos cinereus": true,
	"photocopier": true,
	"piano accordion": true,
	"pick": true,
	"pickelhaube": true,
	"picket fence": true,
	"pickup": true,
	"pickup truck": true,
	"picture palace": true,
	"pier": true,
	"pig": true,
	"pigboat": true,
	"piggy bank": true,
	"pill bottle": true,
	"pillow": true,
	"pineapple": true,
	"ping-pong ball": true,
	"pinwheel": true,
	"pipe organ": true,
	"pirate": true,
	"pirate ship": true,
	"pismire": true,
	"pitcher": true,
	"pizza": true,
	"pizza pie": true,
	"pj\\": true,
	"plane": true,
	"planetarium": true,
	"plaque": true,
	"plastic bag": true,
	"plate": true,
	"plate rack": true,
	"platyhelminth": true,
	"platypus": true,
	"plectron": true,
	"plectrum": true,
	"plinth": true,
	"plough": true,
	"plow": true,
	"plumber\\": true,
	"plunger": true,
	"pocketbook": true,
	"poke bonnet": true,
	"polar bear": true,
	"polaroid camera": true,
	"polaroid land camera": true,
	"pole": true,
	"polecat": true,
	"police van": true,
	"police wagon": true,
	"polyplacophore": true,
	"polyporus frondosus": true,
	"pomegranate": true,
	"pomeranian": true,
	"poncho": true,
	"pongo pygmaeus": true,
	"pool table": true,
	"pop bottle": true,
	"popsicle": true,
	"porcupine": true,
	"porphyrio porphyrio": true,
	"postbag": true,
	"pot": true,
	"potpie": true,
	"potter\\": true,
	"power drill": true,
	"prairie chicken": true,
	"prairie fowl": true,
	"prairie grouse": true,
	"prairie wolf": true,
	"prayer mat": true,
	"prayer rug": true,
	"press": true,
	"pretzel": true,
	"printer": true,
	"prison": true,
	"prison house": true,
	"proboscis monkey": true,
	"projectile": true,
	"projector": true,
	"promontory": true,
	"psittacus erithacus": true,
	"ptarmigan": true,
	"puck": true,
	"puff": true,
	"puff adder": true,
	"puffer": true,
	"pufferfish": true,
	"pug": true,
	"pug-dog": true,
	"puma": true,
	"punch bag": true,
	"punchball": true,
	"punching bag": true,
	"punching ball": true,
	"purse": true,
	"pyjama": true,
	"python sebae": true,
	"quail": true,
	"quill": true,
	"quill pen": true,
	"quilt": true,
	"r.v.": true,
	"race car": true,
	"racer": true,
	"racing car": true,
	"racket": true,
	"racquet": true,
	"radiator": true,
	"radiator grille": true,
	"radio": true,
	"radio reflector": true,
	"radio telescope": true,
	"rain barrel": true,
	"ram": true,
	"rana catesbeiana": true,
	"rapeseed": true,
	"reaper": true,
	"recreational vehicle": true,
	"red fox": true,
	"red hot": true,
	"red panda": true,
	"red setter": true,
	"red wine": true,
	"red wolf": true,
	"red-backed sandpiper": true,
	"red-breasted merganser": true,
	"redbone": true,
	"redshank": true,
	"reel": true,
	"reflex camera": true,
	"refrigerator": true,
	"remote": true,
	"remote control": true,
	"respirator": true,
	"restaurant": true,
	"revolver": true,
	"rhinoceros beetle": true,
	"rhodesian ridgeback": true,
	"ribbed toad": true,
	"ricksha": true,
	"rickshaw": true,
	"rifle": true,
	"rig": true,
	"ring armor": true,
	"ring mail": true,
	"ring snake": true,
	"ring-binder": true,
	"ring-necked snake": true,
	"ring-tailed lemur": true,
	"ringlet": true,
	"ringlet butterfly": true,
	"ringneck snake": true,
	"ringtail": true,
	"river horse": true,
	"roach": true,
	"robin": true,
	"rock beauty": true,
	"rock crab": true,
	"rock lobster": true,
	"rock python": true,
	"rock snake": true,
	"rocker": true,
	"rocking chair": true,
	"rocky": true,
	"rocky mountain bighorn": true,
	"rose hip": true,
	"rosehip": true,
	"rotisserie": true,
	"rottweiler": true,
	"roundabout": true,
	"roundworm": true,
	"rubber": true,
	"rubber eraser": true,
	"rucksack": true,
	"ruddy turnstone": true,
	"ruffed grouse": true,
	"rugby ball": true,
	"rule": true,
	"ruler": true,
	"running shoe": true,
	"russian wolfhound": true,
	"rv": true,
	"sabot": true,
	"safe": true,
	"safety pin": true,
	"saimiri sciureus": true,
	"saint bernard": true,
	"salamandra salamandra": true,
	"salt shaker": true,
	"saltshaker": true,
	"saluki": true,
	"samoyed": true,
	"samoyede": true,
	"sand bar": true,
	"sand viper": true,
	"sandal": true,
	"sandbar": true,
	"sarong": true,
	"sawmill": true,
	"sax": true,
	"saxophone": true,
	"scabbard": true,
	"scale": true,
	"schipperke": true,
	"school bus": true,
	"schooner": true,
	"sciurus niger": true,
	"scooter": true,
	"scope": true,
	"scoreboard": true,
	"scorpion": true,
	"scotch terrier": true,
	"scottie": true,
	"scottish deerhound": true,
	"scottish terrier": true,
	"screen": true,
	"screw": true,
	"screwdriver": true,
	"scuba diver": true,
	"sea": true,
	"sea anemone": true,
	"sea cradle": true,
	"sea cucumber": true,
	"sea lion": true,
	"sea slug": true,
	"sea snake": true,
	"sea star": true,
	"sea urchin": true,
	"sea wolf": true,
	"sea-coast": true,
	"seacoast": true,
	"sealyham": true,
	"sealyham terrier": true,
	"seashore": true,
	"seat belt": true,
	"seatbelt": true,
	"seawall": true,
	"sewing machine": true,
	"shades": true,
	"shako": true,
	"shetland": true,
	"shetland sheep dog": true,
	"shetland sheepdog": true,
	"shield": true,
	"shih-tzu": true,
	"shoe shop": true,
	"shoe store": true,
	"shoe-shop": true,
	"shoji": true,
	"shopping basket": true,
	"shopping cart": true,
	"shovel": true,
	"shower cap": true,
	"shower curtain": true,
	"siamang": true,
	"siamese": true,
	"siamese cat": true,
	"siberian husky": true,
	"sidewinder": true,
	"silky terrier": true,
	"silver salmon": true,
	"site": true,
	"six-gun": true,
	"six-shooter": true,
	"ski": true,
	"ski mask": true,
	"skillet": true,
	"skunk": true,
	"sleeping bag": true,
	"sleuthhound": true,
	"slide rule": true,
	"sliding door": true,
	"slipstick": true,
	"slot": true,
	"sloth bear": true,
	"slug": true,
	"smoothing iron": true,
	"snail": true,
	"snake fence": true,
	"snake-rail fence": true,
	"snoek": true,
	"snooker table": true,
	"snorkel": true,
	"snow leopard": true,
	"snowbird": true,
	"snowmobile": true,
	"snowplough": true,
	"snowplow": true,
	"soap dispenser": true,
	"soccer ball": true,
	"sock": true,
	"soda bottle": true,
	"soft-coated wheaten terrier": true,
	"solar collector": true,
	"solar dish": true,
	"solar furnace": true,
	"sombrero": true,
	"sorrel": true,
	"soup bowl": true,
	"space bar": true,
	"space heater": true,
	"space shuttle": true,
	"spaghetti squash": true,
	"spatula": true,
	"speaker": true,
	"speaker unit": true,
	"speedboat": true,
	"spider monkey": true,
	"spider web": true,
	"spider\\": true,
	"spike": true,
	"spindle": true,
	"spiny anteater": true,
	"spiny lobster": true,
	"spiral": true,
	"spoonbill": true,
	"sport car": true,
	"sports car": true,
	"spot": true,
	"spotlight": true,
	"spotted salamander": true,
	"squealer": true,
	"squeeze box": true,
	"squirrel monkey": true,
	"st bernard": true,
	"staffordshire bull terrier": true,
	"staffordshire bullterrier": true,
	"staffordshire terrier": true,
	"stage": true,
	"standard poodle": true,
	"standard schnauzer": true,
	"starfish": true,
	"station": true,
	"station wagon": true,
	"steam locomotive": true,
	"steel arch bridge": true,
	"steel drum": true,
	"stethoscope": true,
	"stick insect": true,
	"stingray": true,
	"stinkhorn": true,
	"stole": true,
	"stone wall": true,
	"stop watch": true,
	"stoplight": true,
	"stopwatch": true,
	"stove": true,
	"strainer": true,
	"strawberry": true,
	"street sign": true,
	"streetcar": true,
	"stretcher": true,
	"strix nebulosa": true,
	"struthio camelus": true,
	"studio couch": true,
	"stupa": true,
	"sturgeon": true,
	"sub": true,
	"submarine": true,
	"suit": true,
	"suit of clothes": true,
	"sulfur butterfly": true,
	"sulphur butterfly": true,
	"sulphur-crested cockatoo": true,
	"sun blocker": true,
	"sunblock": true,
	"sundial": true,
	"sunglass": true,
	"sunglasses": true,
	"sunscreen": true,
	"sus scrofa": true,
	"suspension bridge": true,
	"sussex spaniel": true,
	"swab": true,
	"sweatshirt": true,
	"sweet potato": true,
	"swimming cap": true,
	"swimming trunks": true,
	"swing": true,
	"switch": true,
	"swob": true,
	"sydney silky": true,
	"symphalangus syndactylus": true,
	"syringe": true,
	"syrinx": true,
	"t-shirt": true,
	"tabby": true,
	"tabby cat": true,
	"table lamp": true,
	"tailed frog": true,
	"tailed toad": true,
	"tam-tam": true,
	"tandem": true,
	"tandem bicycle": true,
	"tank": true,
	"tank suit": true,
	"tape player": true,
	"taper": true,
	"tarantula": true,
	"taxi": true,
	"taxicab": true,
	"teapot": true,
	"teddy": true,
	"teddy bear": true,
	"tee shirt": true,
	"television": true,
	"television system": true,
	"ten-gallon hat": true,
	"tench": true,
	"tennis ball": true,
	"terrace": true,
	"terrapin": true,
	"thalarctos maritimus": true,
	"thatch": true,
	"thatched roof": true,
	"theater curtain": true,
	"theatre curtain": true,
	"thimble": true,
	"thrasher": true,
	"three-toed sloth": true,
	"thresher": true,
	"threshing machine": true,
	"throne": true,
	"thunder snake": true,
	"tibetan mastiff": true,
	"tibetan terrier": true,
	"tick": true,
	"tiger": true,
	"tiger beetle": true,
	"tiger cat": true,
	"tiger shark": true,
	"tile roof": true,
	"timber wolf": true,
	"tin opener": true,
	"tinca tinca": true,
	"titi": true,
	"titi monkey": true,
	"toaster": true,
	"tobacco shop": true,
	"tobacconist": true,
	"tobacconist shop": true,
	"toilet paper": true,
	"toilet seat": true,
	"toilet tissue": true,
	"tope": true,
	"torch": true,
	"torpedo": true,
	"totem pole": true,
	"toucan": true,
	"tow car": true,
	"tow truck": true,
	"toy poodle": true,
	"toy terrier": true,
	"toyshop": true,
	"trackless trolley": true,
	"tractor": true,
	"tractor trailer": true,
	"traffic light": true,
	"traffic signal": true,
	"trailer truck": true,
	"tram": true,
	"tramcar": true,
	"transverse flute": true,
	"trash can": true,
	"tray": true,
	"tree frog": true,
	"tree-frog": true,
	"trench coat": true,
	"triceratops": true,
	"tricycle": true,
	"trifle": true,
	"trike": true,
	"trilobite": true,
	"trimaran": true,
	"tringa totanus": true,
	"tripod": true,
	"triturus vulgaris": true,
	"triumphal arch": true,
	"trolley": true,
	"trolley car": true,
	"trolley coach": true,
	"trolleybus": true,
	"trombone": true,
	"trucking rig": true,
	"trump": true,
	"trumpet": true,
	"tub": true,
	"tup": true,
	"turdus migratorius": true,
	"turnstile": true,
	"tusker": true,
	"two-piece": true,
	"tympan": true,
	"typewriter keyboard": true,
	"u-boat": true,
	"umbrella": true,
	"unicycle": true,
	"upright": true,
	"upright piano": true,
	"urocyon cinereoargenteus": true,
	"ursus americanus": true,
	"ursus arctos": true,
	"ursus maritimus": true,
	"ursus ursinus": true,
	"vacuum": true,
	"vacuum cleaner": true,
	"vale": true,
	"valley": true,
	"vase": true,
	"vat": true,
	"vault": true,
	"velocipede": true,
	"velvet": true,
	"vending machine": true,
	"vestment": true,
	"viaduct": true,
	"vine snake": true,
	"violin": true,
	"violoncello": true,
	"virginia fence": true,
	"vizsla": true,
	"volcano": true,
	"volleyball": true,
	"volute": true,
	"vulpes macrotis": true,
	"vulpes vulpes": true,
	"vulture": true,
	"waffle iron": true,
	"wagon": true,
	"walker foxhound": true,
	"walker hound": true,
	"walking stick": true,
	"walkingstick": true,
	"wall clock": true,
	"wallaby": true,
	"wallet": true,
	"wardrobe": true,
	"warplane": true,
	"warragal": true,
	"warrigal": true,
	"warthog": true,
	"wash-hand basin": true,
	"washbasin": true,
	"washbowl": true,
	"washer": true,
	"washing machine": true,
	"wastebin": true,
	"water bottle": true,
	"water buffalo": true,
	"water hen": true,
	"water jug": true,
	"water ouzel": true,
	"water ox": true,
	"water snake": true,
	"water tower": true,
	"wax light": true,
	"weasel": true,
	"web site": true,
	"website": true,
	"weevil": true,
	"weighing machine": true,
	"weimaraner": true,
	"welcome mat": true,
	"welsh springer spaniel": true,
	"west highland white terrier": true,
	"wheelbarrow": true,
	"whippet": true,
	"whiptail": true,
	"whiptail lizard": true,
	"whirligig": true,
	"whiskey jug": true,
	"whistle": true,
	"white fox": true,
	"white shark": true,
	"white stork": true,
	"white wolf": true,
	"whorl": true,
	"wig": true,
	"wild boar": true,
	"window screen": true,
	"window shade": true,
	"windsor tie": true,
	"wine bottle": true,
	"wing": true,
	"wire-haired fox terrier": true,
	"wireless": true,
	"wok": true,
	"wolf spider": true,
	"wombat": true,
	"wood pussy": true,
	"wood rabbit": true,
	"wooden spoon": true,
	"wool": true,
	"woolen": true,
	"woollen": true,
	"worm fence": true,
	"worm snake": true,
	"wreck": true,
	"wrecker": true,
	"xylophone": true,
	"yawl": true,
	"yellow lady\\": true,
	"yorkshire terrier": true,
	"yurt": true,
	"zebra": true,
	"zucchini": true,
}
