// Cosmetic emoji per item, keyed by the item's label from whichever
// detector recognizes it (COCO-SSD or MobileNet — see lib/detector.ts). A
// generic fallback covers any label added later without a matching entry.
const ICONS: Record<string, string> = {
  chair: '🪑',
  cup: '🥤',
  book: '📖',
  clock: '🕐',
  laptop: '💻',
  bottle: '🧴',
  car: '🚗',
  bicycle: '🚲',
  'traffic light': '🚦',
  dog: '🐶',
  backpack: '🎒',
  bench: '🛋️',
  keyboard: '⌨️',
  remote: '📺',
  vase: '🏺',
  scissors: '✂️',
  'teddy bear': '🧸',
  'potted plant': '🪴',
  bus: '🚌',
  truck: '🚚',
  motorcycle: '🏍️',
  'stop sign': '🛑',
  'fire hydrant': '🚒',
  umbrella: '☂️',
  bird: '🐦',
  cat: '🐱',
  horse: '🐴',
  sheep: '🐑',
  cow: '🐮',
  bear: '🐻',
  frisbee: '🥏',
  kite: '🪁',
  'sports ball': '⚽',
  skis: '🎿',
  snowboard: '🏂',
  broccoli: '🥦',
  carrot: '🥕',
  banana: '🍌',
  apple: '🍎',
  orange: '🍊',
  sandwich: '🥪',
  'cell phone': '📱',
  knife: '🔪',
  fork: '🍴',
  spoon: '🥄',
  bowl: '🥣',
  boat: '⛵',
  suitcase: '🧳',
  'wine glass': '🍷',
  'hot dog': '🌭',
  pizza: '🍕',
  donut: '🍩',
  cake: '🍰',
  couch: '🛋️',
  bed: '🛏️',
  'dining table': '🍽️',
  toilet: '🚽',
  tv: '📺',
  toothbrush: '🪥',
  handbag: '👜',
  'mountain tent': '⛺',
  'sleeping bag': '🛌',
  'cowboy boot': '🥾',
  hatchet: '🪓',
  canoe: '🛶',
  'magnetic compass': '🧭',
  torch: '🔦',
  daisy: '🌼',
  mushroom: '🍄',
  acorn: '🌰',
  bookcase: '📚',
  candle: '🕯️',
  broom: '🧹',
  'frying pan': '🍳',
  teapot: '🫖',
  sunglasses: '🕶️',
  ambulance: '🚑',
  'fire engine': '🚒',
  taxi: '🚕',
  jeep: '🚙',
  minivan: '🚐',
  pickup: '🛻',
  'sports car': '🏎️',
  mailbox: '📫',
  'shopping cart': '🛒',
  'fox squirrel': '🐿️',
  'wood rabbit': '🐰',
  'red fox': '🦊',
  'great grey owl': '🦉',
  'american robin': '🐦',
  goose: '🪿',
  ladybug: '🐞',
  'monarch butterfly': '🦋',
  snail: '🐌',
  'box turtle': '🐢',
  'garden spider': '🕷️',
  'walking stick': '🦯',
  'folding chair': '🪑',
}

export function itemEmoji(label: string): string {
  return ICONS[label] ?? '📦'
}
